name: Python application

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        REACT_APP_MAPS_KEY: ${{ secrets.MAPS_KEY }}
    steps:
    - run: export REACT_APP_MAPS_KEY='${{ secrets.MAPS_KEY }}'
    - uses: actions/checkout@v2
    - name: Login to Heroku Container registry
      run: heroku container:login
    - name: Build and push
      run: heroku container:push -a mapsonmaps web
    - name: Release
      run: heroku container:release -a mapsonmaps web
      
